{
 "title": "Worker Jobs Overview",
 "tags": [
  "ruby",
  "worker"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(ruby_collector_working, namespace)"
   },
   {
    "name": "app",
    "label": "App",
    "query": "label_values(ruby_collector_working, app_kubernetes_io_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Jobs Rate Per Application Worker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Jobs Per Minute" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(ruby_sidekiq_jobs_total{namespace=~\"$namespace\",app_kubernetes_io_name=~\"$app\"})) by (app) ) * 60",
     "legendFormat": "{{app}} "
    }
   ]
  },
  {
   "title": "Failed Jobs Rate As % Of Total Jobs By Worker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit", "label": "Jobs Failure Rate" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ruby_sidekiq_failed_jobs_total{namespace=~\"$namespace\",app=~\"$app\"})) by (job_name, app) / sum(rate(ruby_sidekiq_jobs_total{namespace=~\"$namespace\",app=~\"$app\"})) by (job_name, app) ",
     "legendFormat": "{{app}} : {{job_name}}"
    }
   ]
  },
  {
   "title": "Restarted/Dead Jobs per Worker",
   "type": "graph",
   "description": "Restarted/Dead Sidekiq jobs count",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Restarted/Dead Jobs Count" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ruby_sidekiq_restarted_jobs_total{namespace=~\"$namespace\",app_kubernetes_io_name=~\"$app\"}[1m])) by (app)",
     "legendFormat": "{{app}} : Restarted"
    },
    {
     "expr": "sum(rate(ruby_sidekiq_dead_jobs_total{namespace=~\"$namespace\",app_kubernetes_io_name=~\"$app\"}[1m])) by (app)",
     "legendFormat": "{{app}} : Dead"
    }
   ]
  }
 ]
}