apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "grafana-ingress.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "grafana-ingress.name" . }}
    helm.sh/chart: {{ include "grafana-ingress.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
spec:
  hosts:
    {{- toYaml .Values.hosts | nindent 6 }}
  gateways:
    - {{ include "grafana-ingress.fullname" . }}-gateway
  http:
    - route:
      - destination:
          host: "{{ .Values.host }}"
          port:
            number: 80
