persistence:
  enabled: true
  size: 20Gi
  accessModes:
  - ReadWriteOnce
deploymentStrategy:
  type: Recreate
service:
  type: ClusterIP
resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
admin:
  existingSecret: grafana-credentials
  userKey: username
  passwordKey: password
sidecar:
  dashboards:
    enabled: true
    folder: /var/lib/grafana/dashboards/
    provider:
      provider.yaml:
        apiVersion: 1
        providers:
        - name: 'kubernetes'
          orgId: 1
          folder: 'Kubernetes'
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/kubernetes
        - name: 'aws'
          orgId: 1
          folder: 'AWS'
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/aws
        - name: 'logs'
          orgId: 1
          folder: 'Logs'
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/logs
        - name: 'rails'
          orgId: 1
          folder: 'Rails Application'
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/rails
        - name: 'vm'
          orgId: 1
          folder: 'Victoria Metrics'
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/vm
        - name: 'istio'
          orgId: 1
          folder: 'Istio'
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/istio
  datasources:
    enabled: true
    label: grafana_datasource
plugins:
- grafana-piechart-panel
env:
  GODEBUG: netdns=go
