persistence:
  enabled: true
  size: 20Gi
  accessModes:
  - ReadWriteOnce
deploymentStrategy:
  type: Recreate
service:
  type: ClusterIP
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
admin:
  existingSecret: grafana-credentials
  userKey: username
  passwordKey: password
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
  datasources:
    enabled: true
    label: grafana_datasource
plugins:
  - grafana-piechart-panel
env:
  GODEBUG: netdns=go
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'Kubernetes'
      orgId: 1
      folder: 'Kubernetes'
      type: file
      disableDeletion: false
      editable: false
      options:
        path: /tmp/dashboards/kubernetes
    - name: 'AWS'
      orgId: 1
      folder: 'AWS'
      type: file
      disableDeletion: false
      editable: false
      options:
        path: /tmp/dashboards/aws
    - name: 'Logs'
      orgId: 1
      folder: 'Logs'
      type: file
      disableDeletion: false
      editable: false
      options:
        path: /tmp/dashboards/logs
    - name: 'Rails'
      orgId: 1
      folder: 'Rails Application'
      type: file
      disableDeletion: false
      editable: false
      options:
        path: /tmp/dashboards/rails

