persistence:
  enabled: true
  size: 20Gi
  accessModes:
  - ReadWriteOnce
deploymentStrategy:
  type: Recreate
service:
  type: ClusterIP
resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
admin:
  existingSecret: grafana-credentials
  userKey: username
  passwordKey: password
sidecar:
  dashboards:
    enabled: true
  datasources:
    enabled: true
    label: grafana_datasource
plugins:
- grafana-piechart-panel
env:
  GODEBUG: netdns=go
