{
 "title": "Container Resource Usage",
 "tags": [
  "cpu",
  "memory"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(container_cpu_system_seconds_total{namespace=~\"$namespace\"},container)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",container=~\"$container\",resource=\"cpu\"}) ",
     "legendFormat": "Limits CPU Core"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",container=~\"$container\",resource=\"cpu\"})",
     "legendFormat": "Requested CPU Core"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container_name=~\"$container\"}))",
     "legendFormat": "Usage CPU Cores"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes", "label": "RAM" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",container=~\"$container\",resource=\"memory\"})",
     "legendFormat": "Limit RAM"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",container=~\"$container\",resource=\"memory\"})",
     "legendFormat": "Requested RAM"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\",container_name=~\"$container\"})",
     "legendFormat": "Usage RAM"
    }
   ]
  },
  {
   "title": "CPU Usage by Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=~\"$container\", namespace=~\"$namespace\"})) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name=~\"$container\", namespace=~\"$namespace\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(container_memory_working_set_bytes{container_name=~\"$container\", namespace=~\"$namespace\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container Memory Saturation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", container_name=~\"$container\"}) by (container_name) / sum(label_join(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", container=~\"$container\"},\n    \"container_name\", \"\", \"container\")) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Claim Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}/kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"})*100",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}